Library/Models/Book.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
  public class Book
  {
    public int BookId { get; set; }
    [Required(ErrorMessage = "The book's synopsis can't be empty!")]
    public string BookName { get; set; }
    [Range(1, int.MaxValue, ErrorMessage = "You must add your book to a Catalog.")]
    public int Copies { get; set; }
    public int MaxCopies { get; set; }
    public int CatalogId { get; set; }
    public Catalog Catalog {get; set; }
    public List<AuthorBook> JoinEntities { get; } 
    public List<UserBook> JoinEntities2 { get; }
    
  }
}

Library/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Library.Models;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace Library.Controllers
{
  [Authorize]
  public class AuthorsController : Controller
  {
    private readonly LibraryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
  
    public AuthorsController( LibraryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Authors.ToList());
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Author author)
    {
      _db.Authors.Add(author);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      ViewBag.AuthorId = new SelectList(_db.Books, "AuthorId", "AuthorName");
      Author thisAuthor = _db.Authors
                                  .Include(author => author.JoinEntities)
                                  .ThenInclude(join => join.Book)
                                  .FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }

    [Authorize]
    public ActionResult AddBook(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(authors => authors.AuthorId == id);
      ViewBag.BookId = new SelectList(_db.Books, "BookId", "BookName");
      return View(thisAuthor);
    }

    [HttpPost]
    public ActionResult AddBook(Author author, int bookId)
    {
      #nullable enable
      AuthorBook? joinEntity = _db.AuthorBooks.FirstOrDefault(join => (join.BookId == bookId && join.AuthorId == author.AuthorId));
      #nullable disable
      if (joinEntity == null && bookId != 0)
      {
        _db.AuthorBooks.Add(new AuthorBook() { AuthorId = author.AuthorId, BookId = bookId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = author.AuthorId});
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }
    
    [HttpPost]
    public ActionResult Edit(Author author)
    {
      _db.Authors.Update(author);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = author.AuthorId});
    }
    
    [Authorize]
    public ActionResult DeleteJoin(int joinId)
    {
      AuthorBook joinEntry = _db.AuthorBooks.FirstOrDefault(entry => entry.AuthorBookId == joinId);
      int authorId = joinEntry.AuthorId;
      _db.AuthorBooks.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = authorId});
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      return View(thisAuthor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Author thisAuthor = _db.Authors.FirstOrDefault(author => author.AuthorId == id);
      _db.Authors.Remove(thisAuthor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Library/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Library.Models;
// using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Library.Controllers
{
  [Authorize]
  public class BooksController : Controller
  {
    private readonly LibraryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public BooksController(UserManager<ApplicationUser> userManager, LibraryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      // string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      // ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      // List<Book> userBooks = _db.Books
      //                     .Where(entry => entry.User.Id == currentUser.Id)
      //                     .Include(book => book.Catalog)
      //                     .ToList();
      return View(_db.Books.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.CatalogId = new SelectList(_db.Catalogs, "CatalogId", "CatalogName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Book thisBook, int CatalogId, int Copies)
    {
      if (!ModelState.IsValid)
      {
        ViewBag.CatalogId = new SelectList(_db.Catalogs, "CatalogId", "CatalogName");
        return View(thisBook);
      }
      else
      {
        thisBook.MaxCopies = Copies; 
        _db.Books.Add(thisBook);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Book thisBook = _db.Books
          .Include(book => book.Catalog)
          .Include(book => book.JoinEntities)
          .ThenInclude(join => join.Author)
          .FirstOrDefault(book => book.BookId == id);
      return View(thisBook);
    }

    public ActionResult Edit(int id)
    {
      Book thisBook = _db.Books.FirstOrDefault(book => book.BookId == id);
      ViewBag.CatalogId = new SelectList(_db.Catalogs, "CatalogId", "CatalogName");
      return View(thisBook);
    }

    [HttpPost]
    public ActionResult Edit(Book book, int MaxCopies)
    {
      book.Copies = MaxCopies;
      _db.Books.Update(book);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Book thisBook = _db.Books.FirstOrDefault(book => book.BookId == id);
      return View(thisBook);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Book thisBook = _db.Books.FirstOrDefault(book => book.BookId == id);
      _db.Books.Remove(thisBook);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddAuthor(int id)
    {
      Book thisBook = _db.Books.FirstOrDefault(books => books.BookId == id);
      ViewBag.AuthorId = new SelectList(_db.Authors, "AuthorId", "AuthorName");
      return View(thisBook);
    }

    [HttpPost]
    public ActionResult AddAuthor(Book book, int authorId)
    {
      #nullable enable
      AuthorBook? joinEntity = _db.AuthorBooks.FirstOrDefault(join => (join.AuthorId == authorId && join.BookId == book.BookId));
      #nullable disable
      if (joinEntity == null && authorId != 0)
      {
        _db.AuthorBooks.Add(new AuthorBook() { AuthorId = authorId, BookId = book.BookId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = book.BookId });
    }   

    [Authorize]
    public ActionResult Checkout(int id)
    {
      Book thisBook = _db.Books.FirstOrDefault(model => model.BookId == id);
      return View(thisBook);
    }

    [HttpPost]
    public async Task<ActionResult> Checkout(Book book)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      // book.Copies = book.Copies - 1;
      #nullable enable
      UserBook? joinEntity = _db.UserBooks.FirstOrDefault(join => (join.UserId == currentUser.UserName && join.BookId == book.BookId));
      #nullable disable
      if (joinEntity == null)
      {
        Book thisBook = _db.Books.FirstOrDefault(model => model.BookId == book.BookId);
        thisBook.Copies = thisBook.Copies - 1;
        _db.Books.Update(thisBook);
        _db.UserBooks.Add(new UserBook() { UserId = currentUser.UserName, BookId = book.BookId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = book.BookId });
    }

    [HttpPost]
    public ActionResult Return(int joinId)
    {
      UserBook join = _db.UserBooks.FirstOrDefault(entry => entry.UserBookId == joinId);
      Book book = _db.Books.FirstOrDefault(model => model.BookId == join.BookId);
      book.Copies += 1;
      _db.Books.Update(book);
      _db.UserBooks.Remove(join);
      _db.SaveChanges();
      return RedirectToAction("Index", "Account");
    }

    public ActionResult Error(Error error)
    {
      return View(error);
    }

    public ActionResult AddCopy(int id)
    {
      Book thisbook = _db.Books.FirstOrDefault(model => model.BookId == id);
      return View(thisbook);
    }

    [HttpPost]
    public ActionResult AddCopy(Book book, int num)
    {
      if (num == 0)
      {
        Error error = new Error {};
        string errorMessage = "Input Needs To Be A NUMBER Greater Than 0 If You Want To Add Copies!";
        ViewBag.errorMessage1 = errorMessage;
        error.ErrorMessage = errorMessage;
        error.StoredId = book.BookId;
        return RedirectToAction("Error", error);
      }
      Book thisbook = _db.Books.FirstOrDefault(model => model.BookId == book.BookId);
      thisbook.Copies += num;
      thisbook.MaxCopies += num;
      _db.Update(thisbook);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = thisbook.BookId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      AuthorBook joinEntry = _db.AuthorBooks.FirstOrDefault(entry => entry.AuthorBookId == joinId);
      int bookId = joinEntry.BookId;
      _db.AuthorBooks.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new{ id = bookId});
    } 
  }
}

Library/Views/Books/AddAuthor.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models
@model Library.Models.Book


<div class="container">
  <h2>Add an Author</h2>
  
  <h4>Add an Author to this Book: @Html.DisplayFor(model => model.BookName)</h4>
  
  @using (Html.BeginForm())
  {
      @Html.HiddenFor(model => model.BookId)
  
      @Html.Label("Select an Author")
      @Html.DropDownList("AuthorId")
  
      <input type="submit" value="Save" />
  }
  
  <p>@Html.ActionLink("Back to list", "Index")</p>
</div>

Library/Views/Books/AddCopy.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models;
@model Library.Models.Book;


<div class="container">
  <h1>Add Copies to this Book @Model.BookName</h1>
  
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.BookId)
  
    @Html.Label("Enter Number of Copies to Add")
    @Html.TextBox("num")
    <input type="submit" value="Add Copies">
  }
  
  
  <p>@Html.ActionLink("Cancel", "Details", new { id = Model.BookId })</p>
</div>

Library/Views/Books/Checkout.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models
@model Library.Models.Book

<div class="container">
  <h1>Book Checkout</h1>
  
  <h3>Checkout @Html.ActionLink($"{Model.BookName}", "Details")?</h3>
  
  @if (Model.Copies > 0)
  {
    @using (Html.BeginForm())
    {
      @Html.HiddenFor(model => model.BookId)
      @Html.HiddenFor(model => model.BookName)
  
      <input type="submit" value="Checkout" />
    }
  }
  else
  {
    <h4>All @Model.MaxCopies of this book have been checked out! Please come back later! </h4>
  }
  
</div>

Library/Views/Books/Create.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<div class="container">
  <h4>Add a new book</h4>
  
  <p>@Html.ValidationMessageFor(model => model.CatalogId, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
  <p>@Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
  
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.BookName, "Book Name")
    @Html.TextBoxFor(model => model.BookName)
  
    @Html.LabelFor(model => model.Copies, "How many copies?")
    @Html.TextBoxFor(model => model.Copies)
  
    @Html.LabelFor(model => model.CatalogId, "Catalog Id")
    @Html.DropDownList("CatalogId")
    <br>
    <input type="submit" value="Add new book" class="" />
  }
  <p>@Html.ActionLink("Show all books", "Index")</p>
</div>

Library/Views/Books/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Library.Models.Book

<div class="container">
  <h2>Are you sure you want to delete this book?</h2>
  
  @Html.DisplayNameFor(model => model.BookName): @Html.DisplayFor(model => model.BookName)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
  @Html.ActionLink("Back to List", "Index")
</div>

Library/Views/Books/Details.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models
@model Library.Models.Book

<div class="container">
    <h2>Details</h2>
    
    <h3>Details for @Model.BookName</h3>
    <br>
    
    <h4>@Model.Copies out of / @Model.MaxCopies are available.</h4>
    @if (Model.JoinEntities.Count == 0)
    {
      <h4>You haven't assigned an Author to this book! Click @Html.ActionLink("here", "AddAuthor", new { id = Model.BookId }) to add an author to this book!</h4>
    }
    else
    {
      <h4>Author(s):</h4>
      @foreach (AuthorBook joinEntity in Model.JoinEntities)
      {
        <li>@Html.ActionLink($"{joinEntity.Author.AuthorName}", "Details", "Authors")</li>
        @using (Html.BeginForm("DeleteJoin", "Books"))
        {
          @Html.Hidden("joinId", @joinEntity.AuthorBookId)
          <input type="submit" value="Remove" />
        }
      }
    }
    
    <hr>
    <h4>@Html.ActionLink("Add Copies", "AddCopy", new { id = Model.BookId })</h4>
    <br>
    
    <p>@Html.ActionLink("Edit this book", "Edit", new { id = Model.BookId })</p>
    <p>@Html.ActionLink("Checkout this book", "Checkout", new { id = Model.BookId })</p>
    <p>@Html.ActionLink("Back to list", "Index")</p>
    <p>@Html.ActionLink("Add a new Author Here", "AddAuthor", new { id = Model.BookId })</p>
</div>

Library/Views/Books/Edit.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models;
@model Library.Models.Book;

<div class="container">
  <h1>Edit @Model.BookName </h1>
  
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.BookId)
  
    @Html.LabelFor(model => model.BookName, "Name: ")
    @Html.TextBoxFor(model => model.BookName)
  
    @Html.LabelFor(model => model.MaxCopies, "How many copies?")
    @Html.TextBoxFor(model => model.MaxCopies)
  
    @Html.LabelFor(model => model.CatalogId, "Catalog?")
    @Html.DropDownList("CatalogId")
  
    <input type="submit" value="save" />
  }
  
  <p>@Html.ActionLink("Add new Book", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

Library/Views/Books/Index.cshtml
@{
  Layout = "_Layout";
}

@using Library.Models;

<div class="container">
  <h1>All Books: </h1>
  
  @if (@Model.Count == 0)
  {
    <h3>No books have been added yet!</h3>
  }
  else
  {
    <ul>
      @foreach (Book thisBook in Model)
      {
        <li>@Html.ActionLink($"{thisBook.BookName}", "Details", new { id = thisBook.BookId }) Available @thisBook.Copies / out of @thisBook.MaxCopies </li>
      }
    </ul>
  }
  
  <p>@Html.ActionLink("Add new Book", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
  <p>@Html.ActionLink("Your Home Page", "Index", "Account")</p>
</div>